version: "2"
services:
    databases:
        image: 'mcr.microsoft.com/mssql/server'
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=EasvEasv123
        volumes:
            - './drive:/var/opt/mssql'
    API:
        image: ksbackend

